@startuml

title Actor Style: Default - Stick Man

skinparam ActorStyle awesome

left to right direction

"Use the appliction" as (Use)
"Admin the application" as (Manage)
:Main Admin: as Admin

:User: --> (Use)
Admin ..> (Manage)

@enduml