@startuml

title Use Package

left to right direction

actor Guest as g

package Professional {
    actor Chef as c
    actor Food_Critic as fc
}

package Restaurant {
    usecase Eat_Food as UC1
    usecase Pay_for_Food as UC2
    usecase Drink as UC3
    usecase Review as UC4
}

g --> UC1
g --> UC2
g --> UC3
fc --> UC4

@enduml