' Date: 2024/05/25
' Author: Xiaoqi Zhao

@startmindmap
* Diagraming Tool
** Static Drawing
*** Visio
*** draw.io
** Repository Modeling
*** Sparx Enterprise Architect
*** Archi (ArchiMate) Tool
** Diagramming as Code
*** PlantUML
*** Mermaid
** Other Specific Tool
*** Microsoft Project for Gantt Chart
*** FreePlane for Mindmap
@endmindmap