@startsalt
{#
    {/ 
        <b>General
        Fullscreen 
        Behavior
        Saving 
    } |
    {
        { Open image in | ^Smart Mode^ }
        {
            [X] Smooth images when zoomd
            [X] Confirm image deletion
            [ ] Show hidden images
        }
        [X] Smooth images when zoomd
        [X] Confirm image deletion
        [ ] Show hidden images
        ' [Close]
    }
    . | [Close]
}
@endsalt