@startmindmap

Title my first mindmap

* Debian

** Ubuntu
*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDB Neon

** LMDE

** Solydxk

** SteamOS

** Respbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspmbc</s> => Volumio

@endmindmap