@startuml
nwdiag {
    network DMZ {
        address = "210.x.x.x/24"
        web01 [address = "210.x.x.10"]
        web02 [address = "210.x.x.11"]
        web03 [address = "210.x.x.12"]
    }
    network Internal {
        address = "172.x.x.x/24"
        web01 [address = "172.x.x.10"]
        web02 [address = "172.x.x.11"]
        web03 [address = "172.x.x.12"]
        db01
        db02
        db03
    }
    group app01 {
        color = "#FFAAAA"
        web01
        db01
    }
    group app02 {
        web02
        db02
        color = "AAAAFF"
    }
    group app03 {
        web03
        db03
        color = "AAFFAA"
    }
}
@enduml