@startuml

title network diagram

!include <office/Servers/application_server>
!include <c4/c4>

nwdiag {
    network dmz {
        address = "210.x.x.x/24"
        web01 [address = "210.x.x.1, 210.x.x.20", description = "<$application_server>"];
        web02 [address = "210.x.x.1, 210.x.x.20", description = "<$C4>\n web02\n <&print*5>"]
    }
}
@enduml