@startuml
' left to right direction

' Class Definition
class Student {
    Name
}
class Course

package messages {

class Enrollment1 {
    drop()
    cancel()
}
class Enrollment2 {
    drop()
    cancel()
}
}

' Class Relationships
Student "0..*" - "1..*" Course
' (Student, Course) ... messages
(Student, Course) ... Enrollment1
(Student, Course) ... En
@enduml