@startmindmap
* 交规扣分
** 扣1分
*** 不按规定使用灯光的
*** 违反危险报警闪光灯使用规定使用灯光的
*** 不按规定会车的
*** 机动车载货长度超过规定的
*** 机动车载货宽度超过规定的
*** 机动车载货高度超过规定的
*** 驾驶机动车违反禁令标志指示的
*** 驾驶外埠机动车违反进京通行禁令标志指示行驶的
*** 机动车违反禁止标线指示的
*** 驾驶未按规定定期进行安全技术检验的公路客运汽车、旅游客运汽车、危险物品运输车辆以外的机动车上道路行驶的
*** 驾驶未按规定定期进行安全技术检验的公路客运汽车、旅游客运汽车、危险物品运输车辆以外的机动车上道路行驶的
*** 驾驶摩托车，不戴安全头盔的
*** 驾驶机动车在高速公路以外的道路上行驶时，驾驶人未按规定使用安全带的
*** 在禁止掉头的地点掉头的
*** 在禁止左转弯的地点掉头的
*** 在容易发生危险的路段掉头的
*** 掉头时妨碍正常行驶的车辆通行的
*** 掉头时妨碍正常行驶的行人通行的
*** 驾驶机动车在高速公路、城市快速路以外的道路上不按规定倒车的
*** 驾驶擅自改变已登记的结构的载货汽车上道路行驶的
*** 驾驶擅自改变已登记的构造的载货汽车上道路行驶的
*** 驾驶擅自改变已登记的特征的载货汽车上道路行驶的
*** 驾驶载货汽车载物超过最大允许总质量未达到百分之三十的
*** 驾驶校车在高速公路、城市快速路以外的道路上行驶超过规定时速百分之十以上未达到百分之二十的
*** 驾驶中型以上载客汽车在高速公路、城市快速路以外的道路上行驶超过规定时速百分之十以上未达到百分之二十的
*** 驾驶危险物品运输车辆在高速公路、城市快速路以外的道路上行驶超过规定时速百分之十以上未达到百分之二十的
*** 驾驶中型以上载货汽车在高速公路、城市快速路以外的道路上行驶超过规定时速百分之十以上未达到百分之二十的
*** 在高速公路上行驶时，驾驶人未按规定使用安全带的
** 扣3分
*** 从前车右侧超车的
*** 前车左转弯时超车的
*** 前车掉头时超车的
*** 前车超车时超车的
*** 与对面来车有会车可能时超车的
*** 超越执行紧急任务的警车的
*** 超越执行紧急任务的消防车的
*** 超越执行紧急任务的救护车的
*** 超越执行紧急任务的工程救险车的
*** 在铁路道口超车的
*** 在路口超车的
*** 在窄桥超车的
*** 在弯道超车的
*** 在陡坡超车的
*** 在隧道超车的
*** 在人行横道点超车的
*** 在交通流量大的路段超车的
*** 车辆在道路上发生故障不按规定使用警示灯光的
*** 车辆在道路上发生事故不按规定使用警示灯光的
*** 车辆在道路上发生故障不按规定设置警告标志的
*** 车辆在道路上发生事故不按规定设置警告标志的
*** 准备进入环形路口不让已在路口内的机动车先行的
*** 转弯的机动车未让直行的车辆先行的
*** 转弯的机动车未让行人先行的
*** 相对方向行驶的右转弯机动车不让左转弯车辆先行的
*** 机动车通过无灯控或交警指挥的路口，不按交通标志指示优先通行的一方先行的
*** 机动车通过无灯控或交警指挥的路口，不按标线指示让优先通行的一方先行的
*** 机动车通过无灯控、交警指挥、交通标志标线控制的路口，不让右方道路的来车先行的
*** 机动车在发生故障未开启示廓灯的
*** 机动车在发生事故未开启示廓灯的
*** 机动车在发生故障未开启后位灯的
*** 机动车在发生事故未开启后位灯的
*** 不避让执行任务的特种车辆的
*** 驾驶机动车在城市快速路上不按规定车道行驶的
*** 行经人行横道，未减速行驶的
*** 遇行人正在通过人行横道时未停车让行的
*** 行经没有交通信号的道路时，遇行人横过道路未避让的
*** 驾驶不按规定安装机动车号牌的机动车上道路行驶的
*** 连续驾驶危险物品运输车辆以外的载货汽车超过4小时未停车休息的
*** 连续驾驶危险物品运输车辆以外的载货汽车超过4小时停车休息时间少于20分钟的
*** 驾驶未按规定定期进行安全技术检验的公路客运汽车、旅游客运汽车、危险物品运输车辆上道路行驶的
*** 驾驶未按规定定期进行安全技术检验的公路客运汽车、旅游客运汽车、危险物品运输车辆上道路行驶的
*** 驾驶时拨打接听手持电话的
*** 遇前方车辆停车排队等候时借道超车的
*** 遇前方车辆缓慢行驶时借道超车的
*** 遇前方车辆停车排队等候时占用对面车道的
*** 遇前方车辆缓慢行驶时占用对面车道的
*** 遇前方车辆停车排队等候时穿插等候车辆的
*** 遇前方车辆缓慢行驶时穿插等候车辆的
*** 驾驶校车上道路行驶前，未对校车车况是否符合安全技术要求进行检查的
*** 驾驶存在安全隐患的校车上道路行驶的
*** 驾驶载货汽车载物超过最大允许总质量百分之三十以上未达到百分之五十的
*** 驾驶载货汽车违反规定载客的
*** 驾驶校车、公路客运汽车、旅游客运汽车、7座以上载客汽车以外的其他载客汽车载人超过核定人数百分之二十以上未达到百分之五十的
*** 驾驶校车、中型以上载客载货汽车、危险物品运输车辆以外的机动车在高速公路、城市快速路以外的道路上行驶超过规定时速百分之二十以上未达到百分之五十的
*** 驾车时有其他妨碍安全驾驶的行为的
*** 驾驶机动车不按规定避让校车的
*** 驾驶机动车在高速公路、城市快速路以外的道路上逆向行驶的
*** 机动车在高速公路上发生故障或事故后，不按规定使用灯光的
*** 机动车在高速公路上发生故障或事故后，不按规定设置警告标志的
*** 驾驶机动车在高速公路上正常情况下行驶速度低于规定最低时速20%以上的
*** 在高速公路匝道上超车的
*** 在快速公路匝道上超车的
*** 在高速公路上加速车道超车的
*** 在快速路上加速车道超车的
*** 在高速公路上减速车道超车的
*** 在快速路上减速车道超车的
*** 驾驶机动车在高速公路上不按规定车道行驶的
-- 扣6分
--- 在驾驶证暂扣期间仍驾驶机动车的
--- 在驾驶证暂扣期间仍驾驶机动车的
--- 在驾驶证暂扣期间仍驾驶机动车的
--- 在驾驶证暂扣期间仍驾驶机动车的
--- 在驾驶证暂扣期间仍驾驶机动车的
--- 运载危险物品时不按规定的时间行驶的
--- 运载危险物品时不按规定的路线行驶的
--- 运载危险物品时不按规定的速度行驶的
--- 运载危险物品时未悬挂警示标志的
--- 运载危险物品时未采取必要的安全措施的
--- 驾驶公路客运车辆载人超过核定人数未达到百分之二十的
--- 非紧急情况时在城市快速路应急车道上行驶的
--- 校车载人超过核定人数未达20%的
--- 驾驶机动车违反道路交通信号灯通行的
--- 驾驶中型以上载客汽车在城市快速路上行驶超过规定时速未达20％的
--- 驾驶中型以上载货汽车在城市快速路上行驶超过规定时速未达20％的
--- 驾驶校车在城市快速路上行驶超过规定时速未达20％的
--- 驾驶危险物品运输车辆在城市快速路上行驶超过规定时速未达20％的
--- 驾驶中型以上载客汽车在高速公路、城市快速路以外的道路上行驶超过规定时速20%以上未达到50%的
--- 驾驶中型以上载货汽车在高速公路、城市快速路以外的道路上行驶超过规定时速20%以上未达到50%的
--- 驾驶校车在高速公路、城市快速路以外的道路上行驶超过规定时速20%以上未达到50%的
--- 驾驶危险物品运输车辆在高速公路、城市快速路以外的道路上行驶超过规定时速20%以上未达到50%的
--- 运载超限物品时不按规定的时间行驶的
--- 运载超限物品时不按规定的路线行驶的
--- 运载超限物品时不按规定的速度行驶的
--- 驾驶机动车运载超限的不可解体的物品，未悬挂明显标志的
--- 造成致人轻微伤或者财产损失的交通事故后逃逸，尚不构成犯罪的
--- 造成致人轻微伤或者财产损失的交通事故后逃逸，尚不构成犯罪的
--- 机动车驾驶证被扣留期间驾驶机动车的
--- 驾驶载货汽车载物超过最大允许总质量百分之五十以上的
--- 驾驶旅游客运汽车载人超过核定人数未达到百分之二十的
--- 驾驶7座以上载客汽车载人超过核定人数百分之二十以上未达到百分之五十的
--- 驾驶校车、公路客运汽车、旅游客运汽车、7座以上载客汽车以外的其他载客汽车载人超过核定人数百分之五十以上未达到百分之百的
--- 驾驶校车、中型以上载客载货汽车、危险物品运输车辆以外的机动车在城市快速路上行驶超过规定时速百分之二十以上未达到百分之五十的
--- 驾驶校车、中型以上载客载货汽车、危险物品运输车辆以外的机动车在高速公路、城市快速路以外的道路上行驶超过规定时速百分之五十以上的
--- 驾驶机动车运输危险化学品，未经批准进入危险化学品运输车辆限制通行的区域的（处罚主体：公安机关）
--- 非紧急情况时在高速公路应急车道上行驶的
--- 驾驶中型以上载客汽车在高速公路上行驶超过规定时速未达20％的
--- 驾驶中型以上载货汽车在高速公路上行驶超过规定时速未达20％的
--- 驾驶校车在高速公路上行驶超过规定时速未达20％的
--- 驾驶危险物品运输车辆在高速公路上行驶超过规定时速未达20％的
--- 驾驶校车、中型以上载客载货汽车、危险物品运输车辆以外的机动车在高速公路上行驶超过规定时速百分之二十以上未达到百分之五十的
-- 扣9分
--- 驾驶与准驾车型不符的机动车的
--- 驾驶与准驾车型不符的机动车的
--- 驾驶与准驾车型不符的机动车的
--- 驾驶与准驾车型不符的机动车的
--- 驾驶与准驾车型不符的机动车的
--- 驾驶未悬挂机动车号牌的机动车上道路行驶的
--- 故意遮挡机动车号牌的
--- 故意污损机动车号牌的
--- 驾驶机动车在城市快速路行车道上违法停车的
--- 驾驶机动车非紧急情况下在城市快速路应急车道上停车的
--- 连续驾驶中型以上载客汽车超过4小时未停车休息或者停车休息时间少于20分钟的
--- 连续驾驶危险物品运输车辆超过4小时未停车休息或者停车休息时间少于20分钟的
--- 驾驶人未取得校车驾驶资格驾驶校车的
--- 驾驶7座以上载客汽车载人超过核定人数百分之五十以上未达到百分之百的
--- 驾驶校车在高速公路、城市快速路以外的道路上行驶超过规定时速百分之五十以上的
--- 驾驶中型以上载客汽车在高速公路、城市快速路以外的道路上行驶超过规定时速百分之五十以上的
--- 驾驶危险物品运输车辆在高速公路、城市快速路以外的道路上行驶超过规定时速百分之五十以上的
--- 驾驶中型以上载货汽车在高速公路、城市快速路以外的道路上行驶超过规定时速百分之五十以上的
--- 驾驶机动车在高速公路行车道上违法停车的
--- 驾驶机动车非紧急情况下在高速公路应急车道上停车的
-- 扣12分
--- 驾驶公路客运车辆载人超过核定人数20%以上未到达50%的
--- 驾驶公路客运车辆载人超过核定人数50%以上的
--- 饮酒后驾驶机动车的
--- 饮酒后驾驶机动车的
--- 校车载人超过核定人数20%以上的
--- 驾驶中型以上载客汽车在城市快速路上行驶超过规定时速20％以上未达50%的
--- 驾驶中型以上载货汽车在城市快速路上行驶超过规定时速20％以上未达50%的
--- 驾驶校车在城市快速路上行驶超过规定时速20％以上未达50%的
--- 驾驶危险物品运输车辆在城市快速路上行驶超过规定时速20％以上未达50%的
--- 造成致人轻伤以上或者死亡的交通事故后逃逸，尚不构成犯罪的
--- 驾驶机动车在城市快速路上倒车的
--- 驾驶机动车在城市快速路上逆行的
--- 在城市快速路上穿越中央分隔带掉头的
--- 驾驶旅游客运汽车载人超过核定人数百分之二十以上的
--- 驾驶校车、公路客运汽车、旅游客运汽车以外的其他载客汽车载人超过核定人数百分百以上的
--- 驾驶危险物品运输车辆在城市快速路上行驶超过规定时速百分之五十以上的
--- 驾驶校车、中型以上载客载货汽车、危险物品运输车辆以外的机动车在城市快速路上行驶超过规定时速百分之五十以上的
--- 代替实际机动车驾驶人接受交通违法行为处罚和记分牟取经济利益的
--- 驾驶中型以上载客汽车在城市快速路上行驶超过规定时速百分之五十以上的
--- 驾驶中型以上载货汽车在城市快速路上行驶超过规定时速百分之五十以上的
--- 驾驶校车在城市快速路上行驶超过规定时速百分之五十以上的
--- 在高速公路上倒车的
--- 在高速公路上逆行的
--- 在高速公路上穿越中央分隔带掉头的
--- 驾驶中型以上载客汽车在高速公路上行驶超过规定时速20％以上未达50%的
--- 驾驶中型以上载货汽车在高速公路上行驶超过规定时速20％以上未达50%的
--- 驾驶校车在高速公路上行驶超过规定时速20％以上未达50%的
--- 驾驶危险物品运输车辆在高速公路上行驶超过规定时速20％以上未达50%的
--- 驾驶中型以上载客汽车在高速公路上行驶超过规定时速50％的
--- 驾驶中型以上载货汽车在高速公路上行驶超过规定时速50％的
--- 驾驶校车在高速公路上行驶超过规定时速50％的
--- 驾驶危险物品运输车辆在高速公路上行驶超过规定时速50％的
--- 驾驶校车、中型以上载客载货汽车、危险物品运输车辆以外的机动车在高速公路上行驶超过规定时速百分之五十以上的
--- 使用伪造的机动车号牌的
--- 使用变造的机动车号牌的
--- 使用伪造的机动车行驶证的
--- 使用变造的机动车行驶证的
--- 使用伪造的机动车驾驶证的
--- 使用变造的机动车驾驶证的
--- 使用其他车辆的机动车号牌的
--- 使用其他车辆的机动车行驶证的
--- 使用伪造、变造的校车标牌的
@endmindmap