@startsalt
{ {* New | Open File | [] Uncheckedbox | [x] Checkedbox | - | Close | <img:close_all.png> Close All | - | 

Recent Files > {* stinky.pu | ouch.puml | gandalf.wsd } | <disabled> Recent Folders > } | 

Edit > | Source > | Refactor > | Help | [Button]

}
@endsalt