@startuml
sprite $test [8x8/8] {
FFFFFFFFFF000000
FFFFFFFF00FFFFFF
FFFFFFF0FFFFFFFF
FFFFFF0FFFFFFFFF
FFFFFF0FFFFFFFFF
FFFFF0FFFF000FFF
FFFFF0FFF00FFFFF
FFFFF0FFFFFFFF0F
FFFFF0FFFFFFFF0F
FFFFF00FFFFFFF0F
FFFFFF0FFFFFFF00
FFFFFF00FFFFFFFF
FFFFFFF0FFFF00FF
FFFFFFFF0FFFF000
FFFFFFFF00FFFFFF
FFFFFFFFFF00FFFF
}

rectangle "test test" <<$test>> {
    rectangle "1234565" <<$test>> as src
}

@enduml