@startuml
' filename: ecb_06

' Use "skinparam style robustness" to force the EBC shapes
skinparam style robustness
hide stereotypes

class "FormCreateTourGroup" <<boundary>> {
    --
    + enterDetails()
    + displayErrorMsg(: String)
    + displayCompletionMsg(: String)
}

class "TourGroupControl" <<control>> {
    --
    + validateTourGroupData(details)
    + CreateTourGroup(details)
}

class "TourPackage" <<entity>> {
    # packageId (PK): String
    # packageName: String
    # itinerary: String
    # days: int
    # unitPrice: float
    # TourPackageStatus: String
    --
    + checkPackageStatus()
}

class "TourGroup" <<entity>> {
    # tourId (PK): String
    # packageID (FK): String
    # departureDate: date
    # minPeople: int
    # maxPeople: int
    # TourGroupstatus: String
    --
    + checkTourExist()
    + create()
}

' --- Relationships ---

"FormCreateTourGroup" - "TourGroupControl"
"TourGroupControl" --> "TourPackage"
"TourPackage" "1   " o-- "      0..*" "TourGroup"

@enduml