@startuml
' filename: ecb_09

skinparam style robustness

' Hide stereotypes specifically
hide <<boundary>> stereotype
hide <<control>> stereotype
hide <<entity>> stereotype

' Use "together" to keep the icon and box aligned vertically
together {
    boundary "FormCreateTourGroup " as B_Icon
    class "FormCreateTourGroup" as B_Box {
        --
        "FormCreateTourGroup": + enterDetails()
        "FormCreateTourGroup": + displayErrorMsg(: String)
        "FormCreateTourGroup": + displayCompletionMsg(: String)
    }
    B_Icon -[hidden]down- B_Box
}

together {
    control "TourGroupControl " as C_Icon
    class "TourGroupControl" as C_Box {
        --
        "TourGroupControl": + validateTourGroupData(details)
        "TourGroupControl": + CreateTourGroup(details)
    }
    C_Icon -[hidden]down- C_Box
}

together {
    entity "TourPackage " as E1_Icon
    class "TourPackage" as E1_Box {
        "TourPackage": # packageId (PK): String
        "TourPackage": # packageName: String
        "TourPackage": # itinerary: String
        "TourPackage": # days: int
        "TourPackage": # unitPrice: float
        "TourPackage": # TourPackageStatus: String
        --
        "TourPackage": + checkPackageStatus()
    }
    E1_Icon -[hidden]down- E1_Box
}

together {
    entity "TourGroup " as E2_Icon
    class "TourGroup" as E2_Box {
        "TourGroup": # tourId (PK): String
        "TourGroup": # packageID (FK): String
        "TourGroup": # departureDate: date
        "TourGroup": # minPeople: int
        "TourGroup": # maxPeople: int
        "TourGroup": # TourGroupstatus: String
        --
        "TourGroup": + checkTourExist()
        "TourGroup": + create()
    }
    E2_Icon -[hidden]down- E2_Box
}


' --- Relationships ---
' Here connect the boxes to match the diagram's logic

B_Box - C_Box
C_Box --> E1_Box
E1_Box "1" o-- "0..*" E2_Box

@enduml