@startsalt
{
    <color:blue>Just plain text
    [This is my default button]
    [<color:green>This is my grenn button]
    [<color:#9a9a9a>This is my disabled button]
    []<color:red>Unchecked box
    [X] <color:green>Checked box
    "Enter text here        "
    ^This is a droplist^
    ^<color:#9a9a9a>This is a disabled droplist^
    ^<color:red>This is a red droplist^^<color:blue>first choice^
}
@endsalt