@startuml

title Line Style with Label

' definitions
class foo
class bar
class bar1 
class bar2
class bar3
class bar4
class bar5

' add class members
bar1 : [bold]\n[#red]
bar2 : [dashed]\n[#green]
bar3 : [dotted]\n[#FFAAAA]
bar4 : [hidden]
bar5 : [plain]\n[#blue]

' relationships
foo --> bar : ""
' question: how to keep it empty?
foo -[bold,#red]-> bar1 : [bold]\n[#red]
foo -[dashed,#green]-> bar2 : [dashed]\n[#green]
foo -[dotted,#FFAAAA]-> bar3 : [dotted]\n[#FFAAAA]
foo -[hidden]-> bar4 : [hidden]
foo -[plain,#blue]-> bar5 : [plain]\n[#blue]

@enduml