@startwbs
* Business Process Modelling WBS
** Launch the Project
*** Complete Stakeholders Research
*** Initial Implementation Plan
** Design Phase
*** Model of As-Is Processes Completed
**** Modle of As-Is Porcesses Completed1
**** Modle of As-Is Porcesses Completed2
**** Modle of As-Is Porcesses Completed3
*** Measure As-Is Performance Metrics
*** Identify Quick Wins
** Complete Innovate Phase
@endwbs