@startwbs

<style>
wbsDiagram {
    .pink {
        BackgroundColor pink
    }
    .your_style_name {
        BackgroundColor SkyBlue
    }
}
</style>

* this is the partner workpackage
** this is my workpackage <<pink>>
** thsi is another workpackage <<your_style_name>>
@endwbs