@startuml
!include <archimate/Archimate>

Motivation_Stakeholder(StakeholderElement, "Stakeholder\nDescription")

Business_Service(BusinessService, "Business\nService")

Rel_Composition(StakeholderElement, BusinessService, "Description of the relationship")
@enduml