@startuml

archimate #Application "App1" <<application-component>>
archimate #Application "App2" <<application-component>>
archimate #Application "SFTP_Service" <<application-service>>
archimate #Strategy "Capability" <<capability>>

App1 -right-> SFTP_Service 
SFTP_Service .up.|> App2
App2 .right.|> Capability: realizing

@enduml