@startmindmap

<style>
mindmapDiagram {
    boxless {
        FontColor darkgreen
        FontName Impact
        FontSize 30
    }
    .root {
        FontStyle italic
        FontColor red
    }
}
</style>

*_ Linux
    *_ NixOS
        * new
            *_ new
    * Debian
        *_ Ubuntu
            * Linux Mint
            * Kubuntu
            *_ Lubuntu
            * KDE Neon
        * another
        * new
*_ Another Root <<root>>

@endmindmap