@startuml

title Note on Field or Method

object A {
    ~ {static} int = counter
    - date shipping_date
    + void {abstract} start
}

note right of A
    Object level note
end note

note right of A::counter
    This member is
    annotated
end note

note left of A::shipping_date
    This member is
    annotated
end note

note left of A::start
    This method is
    now explained in
    a UML note
end note

@enduml