@startuml
title Packages

package "Classic Collections" #FFAAAA {
    object Object
    object ArrayList
    Object <|-- ArrayList
}

package com.plantuml.mysite {
    object Demo1
    object Demo2
    Demo1 *- Demo2
}

Object <|-- Demo1

package com.plantuml.mysite1 #DDDDDD {}

package com.yasen #cyan {}

ArrayList -- com.plantuml.mysite

@enduml