@startuml

title hide attribute, methods...

object Dummy1 {
    name = "abc"
    myMehtods
}

object Dummy2 {
    hiddenMethod
}

object Dummy3 <<Serializable>> {
    String Name
    Add
}

' hide members
' show Dummy1 fields
' show Dummy1 members
' show Dummy1 methods
' show Dummy1 attributes
' hide Dummy1 methods
' show members
' hide <<Serializable>> circle
' ' hide <<Serializable>> attributes
' hide <<Serializable>> fields
' hide <<Serializable>> methods
' hide Dummy2 circle

@enduml