@startuml
title simple alias
node Node1 as n1
' node "Node 2" as n2
node n2 as "Node 2"
file f1 as "File 1"
cloud c1 as "This
is
a
multiline
cloud
"
cloud c2 [this is
    another
    cloud
]

n1 -> n2
n1 --> f1
f1 -> c1
c1 -> c2
@enduml