@startgantt

[Task1] lasts 20 days
note bottom
    memo1 ...
    memo2 ...
    explanation1 ...
    explanation2 ...
end note
then [Task2] lasts 4 days
-- Separator title --
[M1] happens on 5 days after [Task1]'s end
-- End --
Separator just at [Task1]'s end
@endgantt